name: Build Flet APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - os: ubuntu-latest
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flet & Tools
        run: |
          pip install "flet[cli]" gspread oauth2client
          sudo apt-get update
          sudo apt-get install -y prime-select || true

      - name: Build APK
        run: |
          flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/apk/app-release.apk
